
package view;

import java.awt.Color;

/**
 *
 * @author HP-
 */
public class doctorDash extends javax.swing.JFrame {

    Color DefaultColor,ClickedColor;
    
    public doctorDash() {
        initComponents();
        DefaultColor=new Color(13,36,51);
        ClickedColor=new Color(255,153,0);
        
        appoints.setBackground(DefaultColor);
        appr.setBackground(DefaultColor);
        den.setBackground(DefaultColor);
        viewall.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        viewall = new javax.swing.JPanel();
        view = new javax.swing.JLabel();
        appoints = new javax.swing.JPanel();
        appoint = new javax.swing.JLabel();
        appr = new javax.swing.JPanel();
        approve = new javax.swing.JLabel();
        den = new javax.swing.JPanel();
        deny = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        out = new javax.swing.JLabel();
        panelall = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/cancel.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient Management System");

        menuName.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        menuName.setForeground(new java.awt.Color(255, 255, 255));
        menuName.setText("Doctor Panel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(menuName, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 809, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(menuName)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(13, 36, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        viewall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewallMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewallMousePressed(evt);
            }
        });

        view.setBackground(new java.awt.Color(13, 36, 51));
        view.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("Patient Information");

        javax.swing.GroupLayout viewallLayout = new javax.swing.GroupLayout(viewall);
        viewall.setLayout(viewallLayout);
        viewallLayout.setHorizontalGroup(
            viewallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewallLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(view)
                .addGap(36, 36, 36))
        );
        viewallLayout.setVerticalGroup(
            viewallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewallLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(view)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        appoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                appointsMousePressed(evt);
            }
        });

        appoint.setBackground(new java.awt.Color(13, 36, 51));
        appoint.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        appoint.setForeground(new java.awt.Color(255, 255, 255));
        appoint.setText("Appointments");

        javax.swing.GroupLayout appointsLayout = new javax.swing.GroupLayout(appoints);
        appoints.setLayout(appointsLayout);
        appointsLayout.setHorizontalGroup(
            appointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
            .addGroup(appointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(appointsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(appoint)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        appointsLayout.setVerticalGroup(
            appointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
            .addGroup(appointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(appointsLayout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addComponent(appoint)
                    .addGap(0, 24, Short.MAX_VALUE)))
        );

        appr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apprMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apprMousePressed(evt);
            }
        });

        approve.setBackground(new java.awt.Color(13, 36, 51));
        approve.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        approve.setForeground(new java.awt.Color(255, 255, 255));
        approve.setText("Approved");

        javax.swing.GroupLayout apprLayout = new javax.swing.GroupLayout(appr);
        appr.setLayout(apprLayout);
        apprLayout.setHorizontalGroup(
            apprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(apprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apprLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(approve)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        apprLayout.setVerticalGroup(
            apprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
            .addGroup(apprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apprLayout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(approve)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );

        den.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                denMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                denMousePressed(evt);
            }
        });

        deny.setBackground(new java.awt.Color(13, 36, 51));
        deny.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        deny.setForeground(new java.awt.Color(255, 255, 255));
        deny.setText("Denied");

        javax.swing.GroupLayout denLayout = new javax.swing.GroupLayout(den);
        den.setLayout(denLayout);
        denLayout.setHorizontalGroup(
            denLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(denLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(denLayout.createSequentialGroup()
                    .addGap(0, 125, Short.MAX_VALUE)
                    .addComponent(deny)
                    .addGap(0, 126, Short.MAX_VALUE)))
        );
        denLayout.setVerticalGroup(
            denLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
            .addGroup(denLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(denLayout.createSequentialGroup()
                    .addGap(0, 22, Short.MAX_VALUE)
                    .addComponent(deny)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        out.setBackground(new java.awt.Color(13, 36, 51));
        out.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        out.setForeground(new java.awt.Color(255, 255, 255));
        out.setText("Log Out");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(out)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
            .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoutLayout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(out)
                    .addGap(0, 24, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appoints, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(den, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewall, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(viewall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(appoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(appr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(den, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelall.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelallLayout = new javax.swing.GroupLayout(panelall);
        panelall.setLayout(panelallLayout);
        panelallLayout.setHorizontalGroup(
            panelallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelallLayout.setVerticalGroup(
            panelallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelall)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        
    }//GEN-LAST:event_jPanel3MousePressed

    private void viewallMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallMousePressed
        appoints.setBackground(DefaultColor);
        appr.setBackground(DefaultColor);
        den.setBackground(DefaultColor);
        viewall.setBackground(ClickedColor);
        logout.setBackground(DefaultColor);
        
        menuName.setText("Patient Information");
    }//GEN-LAST:event_viewallMousePressed

    private void appointsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointsMousePressed
        appoints.setBackground(ClickedColor);
        appr.setBackground(DefaultColor);
        den.setBackground(DefaultColor);
        viewall.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
        menuName.setText("Patient Appointments");
    }//GEN-LAST:event_appointsMousePressed

    private void apprMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apprMousePressed
        appoints.setBackground(DefaultColor);
        appr.setBackground(ClickedColor);
        den.setBackground(DefaultColor);
        viewall.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
        menuName.setText("Approved Patiens");
    }//GEN-LAST:event_apprMousePressed

    private void denMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_denMousePressed
        appoints.setBackground(DefaultColor);
        appr.setBackground(DefaultColor);
        den.setBackground(ClickedColor);
        viewall.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
        menuName.setText("Patient Denied");
    }//GEN-LAST:event_denMousePressed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        appoints.setBackground(DefaultColor);
        appr.setBackground(DefaultColor);
        den.setBackground(DefaultColor);
        viewall.setBackground(DefaultColor);
        logout.setBackground(ClickedColor);
    }//GEN-LAST:event_logoutMousePressed

    private void viewallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallMouseClicked
        patientInformation form1 = new patientInformation();
        panelall.removeAll();
        panelall.add(form1).setVisible(true);
    }//GEN-LAST:event_viewallMouseClicked

    private void appointsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointsMouseClicked
       approve app = new approve();
       panelall.removeAll();
       panelall.add(app).setVisible(true);
    }//GEN-LAST:event_appointsMouseClicked

    private void apprMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apprMouseClicked
       patientapproved appro = new patientapproved();
       panelall.removeAll();
       panelall.add(appro).setVisible(true);
    }//GEN-LAST:event_apprMouseClicked

    private void denMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_denMouseClicked
       patientDenied deny = new patientDenied();
       panelall.removeAll();
       panelall.add(deny).setVisible(true);
    }//GEN-LAST:event_denMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        loginStaff log = new loginStaff();
        this.hide();
        log.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctorDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appoint;
    private javax.swing.JPanel appoints;
    private javax.swing.JPanel appr;
    private javax.swing.JLabel approve;
    private javax.swing.JPanel den;
    private javax.swing.JLabel deny;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel menuName;
    private javax.swing.JLabel out;
    private javax.swing.JDesktopPane panelall;
    private javax.swing.JLabel view;
    private javax.swing.JPanel viewall;
    // End of variables declaration//GEN-END:variables

}
